modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
    issueTrackerURL="https://github.com/BlakeBr0/Cucumber/issues"
    modId="cucumber"
    version="${file.jarVersion}"
    # logoFile="examplemod.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/cucumber"
    # credits="Thanks for this example mod goes to Java"
    authors="BlakeBr0"
    displayName="Cucumber Library"
    # updateJSONURL="http://myurl.me/"
    description='''
    A library of shared code that all of my mods depend on.
    '''

  [[dependencies.cucumber]]
      modId="forge"
      mandatory=true
      versionRange="[31.0,)"
      ordering="NONE"
      side="BOTH"
  [[dependencies.cucumber]]
      modId="minecraft"
      mandatory=true
      versionRange="[1.15.2,1.16]"
      ordering="NONE"
      side="BOTH"