modLoader="javafml"
loaderVersion="[42,)"
license="MIT"

[[mods]]
    issueTrackerURL="https://github.com/BlakeBr0/Cucumber/issues"
    modId="cucumber"
    version="${file.jarVersion}"
    # logoFile="examplemod.png"
    displayURL="https://blakesmods.com/cucumber"
    # credits="Thanks for this example mod goes to Java"
    authors="BlakeBr0"
    displayName="Cucumber Library"
    # updateJSONURL="http://myurl.me/"
    description='''
    A library of shared code that all of my mods depend on.
    '''

    [[dependencies.cucumber]]
        modId="forge"
        mandatory=true
        versionRange="[41.0.110,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.cucumber]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.19.1,1.20)"
        ordering="NONE"
        side="BOTH"