modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
    issueTrackerURL="https://github.com/BlakeBr0/Cucumber/issues"
    modId="cucumber"
    version="${mod_version}"
    # logoFile="examplemod.png"
    displayURL="https://blakesmods.com/cucumber"
    # credits="Thanks for this example mod goes to Java"
    authors="BlakeBr0"
    displayName="Cucumber Library"
    updateJSONURL="https://api.blakesmods.com/v2/mods/cucumber/1.21/updates"
    description='''
    A library of shared code that all of my mods depend on.
    '''

    [[mixins]]
        config="cucumber.mixins.json"

    [[dependencies.cucumber]]
        modId="neoforge"
        mandatory=true
        versionRange="[21.0.0-beta,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.cucumber]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.21,1.21.1)"
        ordering="NONE"
        side="BOTH"